### ISSUE TITLE
Question about details map and unet decoder

### ISSUE THREAD

**Issue by caicj15** [damo-vilab/AnyDoor#13]
In the paper, "For the detail maps, we concatenate them with UNet decoder features at each resolution", but usually we add maps from controlnet and frozen the whole unet.
Why do you use "concatenate" and how do you initialize the weights?

**Comment by XavierCHEN34** [comment]
Similar to ControlNet, the features are added with the encoder feature, and then "concatenated" with the decoder feature. "concatenate" might be more suitable when talking about "decoder feature".
