### ISSUE TITLE
Which is the correct DINOv2 checkpoint?

### ISSUE THREAD

**Issue by Syndulla** [damo-vilab/AnyDoor#16]
Hello,

This looks like an excellent piece of work - thank you for sharing.

May i clarify exactly which is the correct DINOv2 checkpoint to download? I thought it was the ViT-L/14 distilled but that throws an error regarding missing keys, so must not be the intended target.

Any and all assistance is appreciated.

All the best

**Comment by XavierCHEN34** [comment]
dinov2_vitg14_pretrain.pth

**Comment by XavierCHEN34** [comment]
We would also consider to release the checkpoints with smaller version DINOs.

**Comment by Syndulla** [comment]
Thank you for the speedy assistance! Much appreciated. Will give that a go!

**Comment by Syndulla** [comment]
For my learning, may I ask what the difference is between the "With registers" and "Without registers" version of the ViT? If you happen to know?

**Comment by Syndulla** [comment]
Am afraid I am still hitting errors with dinov2_vitg14_pretrain.pth.

RuntimeError: Error(s) in loading state_dict for ControlLDM:
        Missing key(s) in state_dict: "betas", "alphas_cumprod", "alphas_cumprod_prev", "sqrt_alphas_cumprod", "sqrt_one_minus_alphas_cumprod", "log_one_minus_alphas_cumprod", "sqrt_recip_alphas_cumprod", "sqrt_recipm1_alphas_cumprod", "posterior_variance", "posterior_log_variance_clipped", "posterior_mean_coef1", "posterior_mean_coef2", "logvar", "model.diffusion_model.time_embed.0.weight", "model.diffusion_model.time_embed.0.bias", "model.diffusion_model.time_embed.2.weight", "model.diffusion_model.time_embed.2.bias", "model.diffusion_model.input_blocks.0.0.weight".etc

Also getting unexpected keys:

Unexpected key(s) in state_dict: "cls_token", "pos_embed", "mask_token", "patch_embed.proj.weight", "patch_embed.proj.bias", "blocks.0.norm1.weight", "blocks.0.norm1.bias", "blocks.0.attn.qkv.weight", "blocks.0.attn.qkv.bias", "blocks.0.attn.proj.weight", "blocks.0.attn.proj.bias", "blocks.0.ls1.gamma", "blocks.0.norm2.weight", "blocks.0.norm2.bias", "blocks.0.mlp.w12.weight".

Any thoughts as to where I might be going wrong?

**Comment by Syndulla** [comment]
Closing as the problem was I was being an idiot and put the wrong path in configs.

**Comment by PlanPersisitentPatient** [comment]
> For my learning, may I ask what the difference is between the "With registers" and "Without registers" version of the ViT? If you happen to know?

I find this place a bit confusing as well, and I was wondering if you could help clarify it for me. Thank you very much.
