### ISSUE TITLE
Is it possible to use DinoV2 Large or Base Model

### ISSUE THREAD

**Issue by sohaibhaider** [damo-vilab/AnyDoor#20]
Is it possible to use DinoV2 Large or Base Model for inference if so what changes do we need to apply?
Training from scratch
OR
Changes in code will be enough to achieve this

Kindly help

**Comment by XavierCHEN34** [comment]
You need to re-train the model, or at least fine-tune the projection linear layer, as the output channel of different versions of DINOv2 varies.
