### ISSUE TITLE
Where should I place the downloaded checkpoints?

### ISSUE THREAD

**Issue by snakeninny** [damo-vilab/AnyDoor#22]
Including:
https://modelscope.cn/api/v1/models/damo/AnyDoor/repo?Revision=master&FilePath=epoch=1-step=8687.ckpt
https://dl.fbaipublicfiles.com/dinov2/dinov2_vitg14/dinov2_vitg14_pretrain.pth
https://huggingface.co/stabilityai/stable-diffusion-2-1/resolve/main/v2-1_768-nonema-pruned.safetensors?download=true

I know `dinov2_vitg14_pretrain.pth` should be placed in `weight: /somewhere/in/dinov2_vitg14_pretrain.pth` mentioned in anydoor.yaml, but what about other checkpoints?
Thank you!

**Comment by XavierCHEN34** [comment]
You could place it wherever you like. Just modify the demo.yaml / inference.yaml for your path. 
If you would like to fine-tune it,  modify the path in run_train_anydoor.py
