### ISSUE TITLE
How DINOv2 encode an image as a global token 1526 dims and a patch token 256*1536

### ISSUE THREAD

**Issue by StudyingLover** [damo-vilab/AnyDoor#3]
Hello! I think this paper is a amazing work , but I have a question  about **3.1. Identity Feature Extraction**.
In paper , you said that 
> We choose the currently strongest self-supervised model DINO-V2 [37] as the backbone of our ID extractor, which encodes image as a global token $T_{g}^{1*1536}$ , and patch tokens$T_{p}^{256*1536}$ . 

But in NINOv2 paper, **Fast and memory-efficient attention.** they said that

>As a consequence, our ViT-g architecture slightly differs from the architecture proposed by Zhai et al. (2022) in order to maximize compute efficiency, and we use an embedding dimension of 1536 with 24 heads (64 dim/head), rather than 1408 with 16 heads (88 dim/head).

I am confused in fact :rofl: because I cant understand how to get patch token.DINO only encode a token **why you can encode an image as so many tokens**.This question may be a bit stupid, I hope you can help me answer it.

**Comment by XavierCHEN34** [comment]
Most of the ViT models give options for returning patch tokens. The following codes are picked from https://github.com/facebookresearch/dinov2/blob/main/dinov2/models/vision_transformer.py

        
        return {
            "x_norm_clstoken": x_norm[:, 0],
            "x_norm_patchtokens": x_norm[:, 1:],
            "x_prenorm": x,
            "masks": masks,
        }

**Comment by ai1361720220000** [comment]
hello, i debug the code and found the context shape output from FrozenDinoV2Encoder is (b, 257, 1024) instead of (b, 256, 1536). Could you help me to explain it?
