### ISSUE TITLE
Will the training data be released？

### ISSUE THREAD

**Issue by longxiangzhang** [damo-vilab/AnyDoor#4]

**Comment by XavierCHEN34** [comment]
This version only uses the open-sourced dataset.

**Comment by Lucca-cherries** [comment]
> This version only uses the open-sourced dataset.

Hi! Do I have to download all the data or only download the data inside `train` dataset/subfolder. I can see from `datasets.yaml` that not all the data were used to train or eval. Is it okay to obtain only the necessary data to fit the path format in `datasets.yaml` and train the model?

For example, for `YoutubeVOS` dataset, I think you used the 2018 version. Is the `train.zip` in this Google Drive (https://drive.google.com/drive/folders/1bI5J1H3mxsIGo7Kp-pPZU8i6rnykOw7f) enough to train the model?

Thanks in advance for your reply.

**Comment by XavierCHEN34** [comment]
To get comparable performance, you need to match all the datasets appearing in "run_train_anydoor.py".

**Comment by jxl0131** [comment]
Hi!
When I try to train AnyDoor, it always takes a long time to load the dataset.
I type in `htop` and find that the dataset loading process only uses ONE cpu. I gauss that your serial sampling of two frames in the video results in inefficient CPU utilization, ultimately leading to prolonged data loading. If you need to train multiple times, you will have to go through a long process of data loading each time. 
Can you perform one-time, parallel preprocessing on the dataset and only load the preprocessed dataset during training?

thanks.
