### ISSUE TITLE
different results between HF demo and inference result for virtual try-on

### ISSUE THREAD

**Issue by zz8615** [damo-vilab/AnyDoor#66]
Huggingface
<img width="594" alt="db6b35e2ead9d9a03a702ab9d2020b59_1233523" src="https://github.com/ali-vilab/AnyDoor/assets/125888705/380f1484-7adb-4349-bc0c-252da1ad3d09">
inference:
<img width="1062" alt="60670d1d435f7f6239ef7d162aa38303_2069387" src="https://github.com/ali-vilab/AnyDoor/assets/125888705/c2315921-de87-4e21-b07e-89750c0ee19e">

Hi, I have run the inference code and the huggingface demo using the same parameters. However, the huggingface demo seems to produce better results. I do understand that the masks are different as one needs to draw the mask by hand on HF. I was wondering if the model weights you released and the model used on HF are the same? What would contribute to the difference?

**Comment by XavierCHEN34** [comment]
The weights are the same.
The difference is that, when you use the validation code, the target masks are extracted by the GT masks, like the vest in this case. This causes the problem that the mask for the vest is not suitable for a T-shirt.  However, when you use the HF demo, you would manually draw the suitable mask for the T-shirt

**Comment by zz8615** [comment]
> The weights are the same. The difference is that, when you use the validation code, the target masks are extracted by the GT masks, like the vest in this case. This causes the problem that the mask for the vest is not suitable for a T-shirt. However, when you use the HF demo, you would manually draw the suitable mask for the T-shirt

Thank you. I was wondering how to enable shape control as well in the code, there is that option on HF.

**Comment by XavierCHEN34** [comment]
You could refer to some snippets at 
https://huggingface.co/spaces/xichenhku/AnyDoor-online/blob/fdd218f324c1a0150611892497acc382d5ca852a/app.py#L191-L194
