### ISSUE TITLE
Getting error while installing Anydoor locally.

### ISSUE THREAD

**Issue by 4yu5h-crtl** [damo-vilab/AnyDoor#70]
E:\AnyDoor>conda env create -f environment.yaml
Channels:
 - defaults
Platform: win-64
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - _openmp_mutex==5.1=1_gnu
  - ca-certificates==2023.08.22=h06a4308_0
  - ld_impl_linux-64==2.38=h1181459_1
  - libffi==3.3=he6710b0_2
  - libgcc-ng==11.2.0=h1234567_1
  - libgomp==11.2.0=h1234567_1
  - libstdcxx-ng==11.2.0=h1234567_1
  - ncurses==6.4=h6a678d5_0
  - openssl==1.1.1w=h7f8727e_0
  - pip==23.3.1=py38h06a4308_0
  - python==3.8.5=h7579374_1
  - readline==8.2=h5eee18b_0
  - sqlite==3.41.2=h5eee18b_0
  - tk==8.6.12=h1ccaba5_0
  - wheel==0.41.2=py38h06a4308_0
  - xz==5.4.5=h5eee18b_0
  - zlib==1.2.13=h5eee18b_0

Current channels:

  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/msys2/win-64

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

WHILE CREATING A CONDA ENVIORNMENT THIS IS THE ERROR I AM GETTING......HOW DO I RESOLVE IT.

**Comment by zongmi** [comment]
@4yu5h-crtl Maybe you should try 
https://github.com/sdbds/AnyDoor-for-windows

**Comment by zhaoqf-cq** [comment]
> @4yu5h-crtl Maybe you should try https://github.com/sdbds/AnyDoor-for-windows

试了... 也是一样的...
PS C:\Users\13725\Desktop\AnyDoor-for-windows> conda env create -f environment.yaml
Channels:
 - defaults
 - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/msys2
 - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
 - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
Platform: win-64
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - zlib==1.2.13=h5eee18b_0
  - xz==5.4.5=h5eee18b_0
  - wheel==0.41.2=py38h06a4308_0
  - tk==8.6.12=h1ccaba5_0
  - sqlite==3.41.2=h5eee18b_0
  - readline==8.2=h5eee18b_0
  - python==3.8.5=h7579374_1
  - pip==23.3.1=py38h06a4308_0
  - openssl==1.1.1w=h7f8727e_0
  - ncurses==6.4=h6a678d5_0
  - libstdcxx-ng==11.2.0=h1234567_1
  - libgomp==11.2.0=h1234567_1
  - libgcc-ng==11.2.0=h1234567_1
  - libffi==3.3=he6710b0_2
  - ld_impl_linux-64==2.38=h1181459_1
  - ca-certificates==2023.08.22=h06a4308_0
  - _openmp_mutex==5.1=1_gnu

Current channels:

  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/msys2/win-64
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/win-64
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
