### ISSUE TITLE
Question about uvo dataset

### ISSUE THREAD

**Issue by Shi-qingyu** [damo-vilab/AnyDoor#71]
Hello, author! I'm grateful for your exceptional work and your contributions to the open-source community. I'm currently working on reproducing the results of anydoor and I'm seeking the source of the **UVO_sparse_train_video_with_interpolation_reorg.json** file within the uvo dataset. I couldn't locate this file in the provided Google Drive directory (https://drive.google.com/drive/folders/1eOIaOdh9dKX-uiPKxe5GG83IsX7pbI0G). Thank you immensely for your guidance and support. Looking forward to your reply!

**Comment by XavierCHEN34** [comment]
If you use UVO dataset, you need to process the json following ./datasets/Preprocess/uvo_process.py

**Comment by Shi-qingyu** [comment]
> If you use UVO dataset, you need to process the json following ./datasets/Preprocess/uvo_process.py

Thank you for your response! I hadn't realized this file was there, haha
