### ISSUE TITLE
DreamBooth benchmarks

### ISSUE THREAD

**Issue by ai1361720220000** [damo-vilab/AnyDoor#73]
Could you share the constructed new benchmark provided by DreamBooth in the paper?

**Comment by XavierCHEN34** [comment]
You could find it here
https://drive.google.com/drive/folders/1XecTGw3hb-gxFvHX3BsGhgpfcAkReDCY?usp=sharing

**Comment by yushenglvzhe** [comment]
> You could find it here你可以在这里找到它。 https://drive.google.com/drive/folders/1XecTGw3hb-gxFvHX3BsGhgpfcAkReDCY?usp=sharing

Hello, the link is not working. Could you share it again?
