### ISSUE TITLE
 The inferred images exhibit severe artifacts, which adversely affect the visual quality.

### ISSUE THREAD

**Issue by kongzijian** [damo-vilab/AnyDoor#74]
<img width="1072" alt="image" src="https://github.com/ali-vilab/AnyDoor/assets/54501511/25393481-6b03-41a0-9f96-7438b8195629">
<img width="600" alt="image" src="https://github.com/ali-vilab/AnyDoor/assets/54501511/5c730eb4-75b5-479b-a0c3-ba5829253510">

When I infer the results of images using my own model, I notice the presence of square-shaped artifacts. Even when using example images provided by the official model for inference, similar artifacts are present (as indicated by the red arrows in the image, showing semi-transparent square artifacts). However, these artifacts are more clearly in my results, severely affecting the visual effect. What could be causing this situation? How can it be avoided?

**Comment by kongzijian** [comment]
I checked the dimensions of the data. The official example input is: 
ref_image.shape is : (1117, 714, 3)
ref_mask.shape is : (1117, 714)
back_image.shape is : (512, 512, 3)
tar_mask.shape is : (512, 512)
unique_ref_mask is : [0 1]
unique_tar_mask is : [0 1]，
Whereas, the input for my own data is: 
ref_image.shape is : (1080, 1920, 3)
ref_mask.shape is : (1080, 1920)
back_image.shape is : (720, 1280, 3)
tar_mask.shape is : (720, 1280)
unique_ref_mask is : [0 1]
unique_tar_mask is : [0 1]
I dnt think the difference between back image  will affect the final output.

**Comment by XavierCHEN34** [comment]
You could remove the operator of "crop and paste back"

**Comment by kongzijian** [comment]
@XavierCHEN34 
This is not a solution to the problem, but rather a way to avoid it. Are there any several methods to eliminate artifacts?

**Comment by XavierCHEN34** [comment]
Currently, it is a common issue that the newly inpainted region would be slightly different from the original pixels. A better VAE, higher resolutions might help.
