### ISSUE TITLE
How to change clothing texture

### ISSUE THREAD

**Issue by ZhangLei999** [damo-vilab/AnyDoor#76]
Great work!
The effect of changing clothes is very good. If I only change the texture of the clothes, but not the style of the clothes. Can you give me some suggestions?
![2024-02-22 15-36-02屏幕截图](https://github.com/ali-vilab/AnyDoor/assets/44597470/36e2c4a4-fcd7-4eec-908c-0ee54a02af9c)

**Comment by XavierCHEN34** [comment]
Maybe you could use additional controls like depth map to fix the shape/style of the garments.
