### ISSUE TITLE
Question about "HF map"

### ISSUE THREAD

**Issue by shoutOutYangJie** [damo-vilab/AnyDoor#83]
![image](https://github.com/ali-vilab/AnyDoor/assets/46734514/6be811be-4225-491f-82c9-9fb17be0858e)

I am curious about why you use controlnet to add "hf map" by the way of element-wise add opertion?
It is very  strange because your result is pose-variational. however, controlnet injects feature by spatial add.

**Comment by XavierCHEN34** [comment]
Hi, you could understand it like a version of ``user scribbles'' in ControlNet with colors. 
It is not strictly a pixel-to-pixel alignment. 
The variations between the generation results and the control signals could be learned by the model. 

<img width="866" alt="image" src="https://github.com/ali-vilab/AnyDoor/assets/32154409/fb21b0db-6300-4df1-9dfa-dbbd83bc5133">
