### ISSUE TITLE
About classifieer-free guidance training.

### ISSUE THREAD

**Issue by Taited** [damo-vilab/AnyDoor#87]
Thank you for your excellent work.

However, I am confused about the unconditional settings. For example, in this [line](https://github.com/ali-vilab/AnyDoor/blob/44ca2b2a70ec2cf107f3d26a5b46def6670fb0a5/cldm/cldm.py#L402), I noticed that you set the unconditional state equal to the conditional ones. Additionally, I did not find any unconditional dropping during your training stage.

Is this an expected implementation in the CFG?

**Comment by XavierCHEN34** [comment]
Hi, this code is uc_concat. however, we make CFG in cross attention for the DINOv2 in

uc_cross = self.get_unconditional_conditioning(N)

**Comment by yankuai** [comment]
> uc_cross = self.get_unconditional_conditioning(N)

I think what you mentioned is for the CFG sampling process (inference), not training. We should randomly drop the image prompt during training, but I didn't find this code in the repo either.
