### ISSUE TITLE
Long dataset processing time during the dataset loading before training.

### ISSUE THREAD

**Issue by jxl0131** [damo-vilab/AnyDoor#89]
Hi!
When I try to train AnyDoor, it always takes a long time to load the dataset.
I type in htop and find that the dataset loading process only uses ONE cpu. I gauss that your serial sampling of two frames in the video results in inefficient CPU utilization, ultimately leading to prolonged data loading. If you need to train multiple times, you will have to go through a long process of data loading each time.
Can you perform one-time, parallel preprocessing on the dataset and only load the preprocessed dataset during training?

What's more, does anyone else have the same question? I am concerned about the long data set loading caused by my improper operation.

thanks.

**Comment by silky1708** [comment]
any resolution?

**Comment by mao-code** [comment]
same problem here
