### ISSUE TITLE
details about vitrual try-on

### ISSUE THREAD

**Issue by monkeyCv** [damo-vilab/AnyDoor#9]
Hi, dear author, thanks for your greate work. I have some problems about virtual try-on. Could you share more information about data producer? How to get the person box on training and test? What is the input of network (not noise) ? Is it the portrait itself, or  portrait with a box mask filled with gray pixel? You use two dataset trainning together, then test on the VitonHD-test, or use only VitonHD-train to train and test single? Trainning virtual try-on, not use other dataset? Thanks very much.

**Comment by jiqizaisikao** [comment]
![WechatIMG54](https://github.com/damo-vila
![WechatIMG55](https://github.com/damo-vilab/AnyDoor/assets/16893734/eb2003fc-6d7c-49d2-a8ee-800c4d6cad56)
b/AnyDoor/assets/16893734/7a71a23a-2ab5-4c4b-8e73-fb476daa5905)
这是我自己模型训练的结果，类似于Adobe的生成填充，微信最新的<换影CP>小程序，根据一张照片，一个模版，进行一键换头，一键换脸型。不过需要不
小的算力进行训练，我可能没有大量资源进行训练优化了，希望可以找到一些朋友进行合作研究和开发

**Comment by jiqizaisikao** [comment]
![WechatIMG2](https://github.com/damo-vilab/AnyDoor/assets/16893734/69aea67b-5d49-4f12-8216-1232af77dafd)

**Comment by jiqizaisikao** [comment]
![WechatIMG58](https://github.com/damo-vilab/AnyDoor/assets/16893734/d18bda4d-051a-4080-9402-e6bc870c6171)
![WechatIMG59](https://github.com/damo-vilab/AnyDoor/assets/16893734/0dddc2fa-4fb4-42ce-8aa8-120a35d17962)

**Comment by Prometheus-first** [comment]
> ![WechatIMG54](https://github.com/damo-vila ![WechatIMG55](https://user-images.githubusercontent.com/16893734/265142903-eb2003fc-6d7c-49d2-a8ee-800c4d6cad56.jpeg) b/AnyDoor/assets/16893734/7a71a23a-2ab5-4c4b-8e73-fb476daa5905) 这是我自己模型训练的结果，类似于Adobe的生成填充，微信最新的<换影CP>小程序，根据一张照片，一个模版，进行一键换头，一键换脸型。不过需要不 小的算力进行训练，我可能没有大量资源进行训练优化了，希望可以找到一些朋友进行合作研究和开发

咱们可以合作，我有A100资源

**Comment by XavierCHEN34** [comment]
The code is released, please refer to the code for the details.  :)
